Feature comment UI & logic
ByYuto/GuideToTheGalaxyFrontend pull request #48
Opened 2021-07-31 00:14 UTC by cristihandev

2021-08-02 15:44 UTC, cacharrin requested changes
Cris, solo veo una cosa rara... y es que el mensaje de que "Es posible que los cambios no se guarden" que aparece cuando uno se va a salir de la pagina o a recargarla... sale siempre... y no debería.
Es decir... si no he escrito nada, puedo recargar sin el mensaje
Si he escrito algo y recargo debería salir el mensaje (actualmente sale)
Pero si borro el mensaje que habia escrito no me debería salir el mensaje, porque no tengo nada pendiente por enviar no?

Es decir, yo escribo "hola" y luego lo borro... y intento recargar... porque debería salirme el mensaje?
Creo que debería salir solo si tengo algo escrito en la caja de comentarios sin enviar, de resto no le veo sentido... o estoy equivocado?

2021-08-02 15:52 UTC, cacharrin commented
Y lo otro que también vi.... es que el popup de login solo sale si uno hace click en la caja... no debería salir siempre que la caja tenga el foco? Si paso el foco a la caja de texto con TAB, el popup de no sale (Y yo si creo que debería no?)

2021-08-02 21:33 UTC, cristihandev commented
Pipe, con respecto al primer comentario, asi es como funciona actualmente...

2021-08-02 21:34 UTC, cristihandev commented
el segundo comentario, esta es la tarea con los requerimientos https://app.clickup.com/t/5z6gzf

2021-08-04 14:34 UTC, cacharrin approved these changes

2021-08-04 14:34 UTC, merged